//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Beneficiaries {
            get {
                object obj = ResourceManager.GetObject("Beneficiaries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Beneficiaries1 {
            get {
                object obj = ResourceManager.GetObject("Beneficiaries1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Beneficiaries2 {
            get {
                object obj = ResourceManager.GetObject("Beneficiaries2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Beneficiaries3 {
            get {
                object obj = ResourceManager.GetObject("Beneficiaries3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cascade {
            get {
                object obj = ResourceManager.GetObject("cascade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap General_Information {
            get {
                object obj = ResourceManager.GetObject("General Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap General_Information1 {
            get {
                object obj = ResourceManager.GetObject("General Information1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap General_Information2 {
            get {
                object obj = ResourceManager.GetObject("General Information2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap General_Information3 {
            get {
                object obj = ResourceManager.GetObject("General Information3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap General_Information4 {
            get {
                object obj = ResourceManager.GetObject("General Information4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsmemberinformationcreate {
            get {
                object obj = ResourceManager.GetObject("lmsmemberinformationcreate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsmemberinformationcreate1 {
            get {
                object obj = ResourceManager.GetObject("lmsmemberinformationcreate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsmemberinformationcreate2 {
            get {
                object obj = ResourceManager.GetObject("lmsmemberinformationcreate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsmemberinformationviewupdate {
            get {
                object obj = ResourceManager.GetObject("lmsmemberinformationviewupdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsofficeemployeercreate {
            get {
                object obj = ResourceManager.GetObject("lmsofficeemployeercreate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsofficeemployeercreate1 {
            get {
                object obj = ResourceManager.GetObject("lmsofficeemployeercreate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsofficeemployeercreate2 {
            get {
                object obj = ResourceManager.GetObject("lmsofficeemployeercreate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsofficeemployeercreate3 {
            get {
                object obj = ResourceManager.GetObject("lmsofficeemployeercreate3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsofficeemployeercreate4 {
            get {
                object obj = ResourceManager.GetObject("lmsofficeemployeercreate4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmsofficeemployeercreate5 {
            get {
                object obj = ResourceManager.GetObject("lmsofficeemployeercreate5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmspersonreferenceviewupdate {
            get {
                object obj = ResourceManager.GetObject("lmspersonreferenceviewupdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmspersonreferenceviewupdate1 {
            get {
                object obj = ResourceManager.GetObject("lmspersonreferenceviewupdate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Personal_Documents {
            get {
                object obj = ResourceManager.GetObject("Personal Documents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Personal_Documents1 {
            get {
                object obj = ResourceManager.GetObject("Personal Documents1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap References {
            get {
                object obj = ResourceManager.GetObject("References", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap References1 {
            get {
                object obj = ResourceManager.GetObject("References1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sidebar {
            get {
                object obj = ResourceManager.GetObject("Sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sidebar1 {
            get {
                object obj = ResourceManager.GetObject("Sidebar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sidebar2 {
            get {
                object obj = ResourceManager.GetObject("Sidebar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
